[project]
name = "jax-neural-odes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "diffrax>=0.7.0",
    "jax>=0.8.0",
    "matplotlib>=3.10.7",
    "optax>=0.2.6",
]
